server:
  port: 0
spring:
  application:
    name: catalog-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: catalog
      port: 27017
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  retry:
    configs:
      default:
        max-retry-attempts: 2
        wait-duration: 2s
        retry-exceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
          - java.net.ConnectException
      instances:
        getMoviesRetry:
          base-config: default
          retry-exceptions:
            - feign.FeignException$InternalServerError
            - feign.FeignException$ServiceUnavailable
        getSeriesRetry:
          base-config: default
          retry-exceptions:
            - feign.FeignException$InternalServerError
            - feign.FeignException$ServiceUnavailable
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 20s
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        sliding-window-type: COUNT_BASED
    instances:
      getMoviesCB:
        base-config: default
      getSeriesCB:
        base-config: default